apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <match *.**>
      @type elasticsearch
      host elasticsearch.default.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix kubernetes
      type_name fluentd
      flush_interval 10s
    </match>