replicaCount: 1
resources:
  limits:
     cpu: 250m
     memory: 256Mi

# helm install my-controller oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller -f ingress-controller.yaml
# helm delete my-controller